
export PATH="/usr/local/bin:$PATH"
export DOTFILES=~/.dotfiles

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Path to Antigen installation from HomeBrew
export ANTIGEN=/usr/local/share/antigen/antigen.zsh

source $DOTFILES/zsh/bootstrap.zsh

# Auto 'ls' when you enter a new folder
auto-ls () { ls; }
chpwd_functions=( auto-ls $chpwd_functions )

# Uncomment to run 'karn update' on every git command
# if which karn > /dev/null; then eval "$(karn init)"; fi

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Get random tips when you open a new tab
# node /Users/sijo/Projects/personal/pragmatic_tips/index.js
