
export DOTFILES=~/.dotfiles
export ANTIGEN=~/.antigen

source $DOTFILES/zsh/bootstrap.zsh

# Auto 'ls' when you enter a new folder
auto-ls () { ls; }
chpwd_functions=( auto-ls $chpwd_functions )

# if which karn > /dev/null; then eval "$(karn init)"; fi

node /Users/sijo/Projects/personal/pragmatic_tips/index.js
